import { Router, Request, Response } from "express";
import { ProductController } from "./../../controllers/product.controller";
const ProductRoutes = Router();
const Product = new ProductController();
ProductRoutes.get('/search',Product.GetProductUsingSearch);
ProductRoutes.get("/images/:name", Product.getImage);
ProductRoutes.get("/page/:page", Product.GetProductsLazy);
ProductRoutes.get("/:id", Product.GetProduct);
ProductRoutes.get("/",Product.GetProducts);
ProductRoutes.put("/:id", Product.UpdateProduct);
ProductRoutes.post("/", Product.CreateProduct);
ProductRoutes.delete("/:id", Product.DeleteProduct);
export default ProductRoutes;
